server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    schema: classpath:datasource/schema.sql
    data: classpath:datasource/data.sql
    sql-script-encoding: UTF-8
    initialization-mode: embedded
    druid:
      driver-class-name: net.sf.log4jdbc.DriverSpy
      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      test-while-idle: false
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
#    #出现错误时, 直接抛出异常
#    throw-exception-if-no-handler-found: true
#  resources:
#    #关闭工程中的资源文件建立映射
#    add-mappings: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  type-enums-package: com.example.demo.util.enums
  global-config:
    db-config:
      id-type: uuid
    banner: false




kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1
